title: (awesome-cl)
description: A curated list of awesome Common Lisp frameworks, libraries and other shiny stuff.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

# Update: 2025-10-05

# Update: 2025-10-06

# Update: 2025-10-10

# Update: 2025-10-17
